export const myAttendance = [
  {
    id: 0,
    event: 'Present',
    clockIn: '08:55 ',
    clockOut: '18:02',
    workingHours: '9h 07m',
    day: 'Mon',
    date: '9',
  },
  {
    id: 1,
    event: 'Present',
    clockIn: '09:01',
    clockOut: '18:15',
    workingHours: '9h 14m',
    day: 'Tue',
    date: '10',
  },
  {
    id: 2,
    event: 'Late',
    clockIn: '09:32',
    clockOut: '18:45 ',
    workingHours: '9h 13m',
    day: 'Wed',
    date: '11',
  },
  {
    id: 3,
    event: 'Present',
    clockIn: '08:55 ',
    clockOut: '18:02 ',
    workingHours: '9h 07m',
    day: 'Thu',
    date: '12',
  },
  {
    id: 4,
    event: 'Leave',
    clockIn: '',
    clockOut: '',
    workingHours: '',
    day: 'Fri',
    date: '13',
  },
  {
    id: 5,
    event: 'Weekend',
    clockIn: '',
    clockOut: '',
    workingHours: '',
    day: 'Sat',
    date: '14',
  },
  {
    id: 6,
    event: 'Weekend',
    clockIn: '',
    clockOut: '',
    workingHours: '',
    day: 'Sun',
    date: '15',
  },
]
