export const teamRequestData = [
  {
    id: 'REQ-301',
    name: 'John Doe',
    type: 'Leave',
    subType: 'Annual Leave',
    day: '3 days',
    date: '2026-03-15',
    status: 'Approved',
  },
  {
    id: 'REQ-302',
    name: 'Aisha Khan',
    type: 'Overtime',
    subType: 'Overtime',
    hours: '4 hours',
    date: '2026-03-08',
    status: 'Approved',
  },
  {
    id: 'REQ-303',
    name: 'Ravi Sharma',
    type: 'Time Correction',
    subType: 'Check-in Correction',
    detail: '09:00 → 08:45',
    date: '2026-03-05',
    status: 'Rejected',
  },
  {
    id: 'REQ-304',
    name: 'Emily Chen',
    type: 'Leave',
    subType: 'Sick Leave',
    day: '1 day',
    date: '2026-02-15',
    status: 'Approved',
  },
  {
    id: 'REQ-305',
    name: 'Michael Smith',
    type: 'Leave',
    subType: 'Sick Leave',
    day: '1 day',
    date: '2026-01-01',
    status: 'Approved',
  },
  {
    id: 'REQ-306',
    name: 'Sita Gurung',
    type: 'Time Correction',
    subType: 'Check-in Correction',
    detail: '09:15 → 09:00',
    date: '2026-02-20',
    status: 'Approved',
  },
  {
    id: 'REQ-307',
    name: 'David Lee',
    type: 'Overtime',
    subType: 'Overtime',
    hours: '2 hours',
    date: '2026-03-10',
    status: 'Pending',
  },
  {
    id: 'REQ-308',
    name: 'Priya Patel',
    type: 'Leave',
    subType: 'Annual Leave',
    day: '5 days',
    date: '2026-03-01',
    status: 'Approved',
  },
];