export const BranchData = [
  {
    id: 0,
    branchId: '002',
    branch: 'Corporate ',
    location: 'Kathmandu',
    createdDate: '2020-12-03',
  },
  {
    id: 1,
    branchId: 'BR001',
    branch: 'Kathmandu Main',
    location: 'Kathmandu',
    createdDate: '2026-03-15',
  },
  {
    id: 2,
    branchId: 'BR002',
    branch: 'Pokhara Branch',
    location: 'Pokhara',
    createdDate: '2026-02-10',
  },
  {
    id: 3,
    branchId: 'BR003',
    branch: 'Lalitpur Branch',
    location: 'Lalitpur',
    createdDate: '2026-01-25',
  },
    {
    id: 4,
    branchId: 'BR004',
    branch: 'Corporate ',
    location: 'Kathmandu',
    createdDate: '2020-12-03',
  },
  {
    id: 5,
    branchId: 'BR005',
    branch: 'Kathmandu Main',
    location: 'Kathmandu',
    createdDate: '2026-03-15',
  },
  {
    id: 6,
    branchId: 'BR006',
    branch: 'Pokhara Branch',
    location: 'Pokhara',
    createdDate: '2026-02-10',
  },
  {
    id: 7,
    branchId: 'BR007',
    branch: 'Lalitpur Branch',
    location: 'Lalitpur',
    createdDate: '2026-01-25',
  },
    {
    id: 8,
    branchId: 'BR008',
    branch: 'Corporate ',
    location: 'Kathmandu',
    createdDate: '2020-12-03',
  },
  {
    id: 9,
    branchId: 'BR009',
    branch: 'Kathmandu Main',
    location: 'Kathmandu',
    createdDate: '2026-03-15',
  },
  {
    id: 10,
    branchId: 'BR010',
    branch: 'Pokhara Branch',
    location: 'Pokhara',
    createdDate: '2026-02-10',
  },
  {
    id: 11,
    branchId: 'BR011',
    branch: 'Lalitpur Branch',
    location: 'Lalitpur',
    createdDate: '2026-01-25',
  },
    {
    id: 12,
    branchId: 'BR012',
    branch: 'Corporate ',
    location: 'Kathmandu',
    createdDate: '2020-12-03',
  },
  {
    id: 13,
    branchId: 'BR013',
    branch: 'Kathmandu Main',
    location: 'Kathmandu',
    createdDate: '2026-03-15',
  },
  {
    id: 14,
    branchId: 'BR014',
    branch: 'Pokhara Branch',
    location: 'Pokhara',
    createdDate: '2026-02-10',
  },
  {
    id: 15,
    branchId: 'BR015',
    branch: 'Lalitpur Branch',
    location: 'Lalitpur',
    createdDate: '2026-01-25',
  },
]
