export const addressData = [
  {
    id: 0,
    country: 'Nepal',
    provinces: [
      {
        id: 0,
        province: 'Koshi',
        districts: {
          id: 0,
          district: [
            'Bhojpur',
            'Dhankuta',
            'Ilam',
            'Jhapa',
            'Khotang',
            'Morang',
            'Okhaldhunga',
            'Panchthar',
            'Sankhuwasabha',
            'Solukhumbu',
            'Sunsari',
            'Taplejung',
            'Terhathum',
            'Udayapur',
          ],
        },
      },
      {
        id: 1,
        province: 'Madhesh',
        districts: {
          id: 1,
          district: [
            'Bara',
            'Dhanusha',
            'Mahottari',
            'Parsa',
            'Saptari',
            'Sarlahi',
            'Siraha',
          ],
        },
      },
      {
        id: 2,
        province: 'Bagmati',
        districts: {
          id: 2,
          district: [
            'Bhaktapur',
            'Chitwan',
            'Dhading',
            'Dolakha',
            'Kathmandu',
            'Kavrepalanchok',
            'Lalitpur',
            'Makwanpur',
            'Nuwakot',
            'Ramechhap',
            'Rasuwa',
            'Sindhuli',
            'Sindhupalchok',
          ],
        },
      },
      {
        id: 3,
        province: 'Gandaki',
        districts: {
          id: 3,
          district: [
            'Baglung',
            'Gorkha',
            'Kaski',
            'Lamjung',
            'Manang',
            'Mustang',
            'Myagdi',
            'Nawalpur',
            'Parbat',
            'Syangja',
            'Tanahun',
          ],
        },
      },
      {
        id: 4,
        province: 'Lumbini',
        districts: {
          id: 4,
          district: [
            'Arghakhanchi',
            'Banke',
            'Bardiya',
            'Dang',
            'Eastern Rukum',
            'Gulmi',
            'Kapilvastu',
            'Parasi',
            'Palpa',
            'Pyuthan',
            'Rolpa',
            'Rupandehi',
          ],
        },
      },
      {
        id: 5,
        province: 'Karnali',
        districts: {
          id: 5,
          district: [
            'Dailekh',
            'Dolpa',
            'Humla',
            'Jajarkot',
            'Jumla',
            'Kalikot',
            'Mugu',
            'Salyan',
            'Surkhet',
            'Western Rukum',
          ],
        },
      },
      {
        id: 6,
        province: 'Sudurpashchim',
        districts: {
          id: 6,
          district: [
            'Achham',
            'Baitadi',
            'Bajhang',
            'Bajura',
            'Dadeldhura',
            'Darchula',
            'Doti',
            'Kanchanpur',
          ],
        },
      },
    ],
  },
]

export const municipalityData = [
  { id:0, content: 'Lalitpur Metropolitan City',value: 'Lalitpur Metropolitan City' },
  { id:1, content: 'Godawari Municipality',value: 'Godawari Municipality' },
  { id:2 , content: 'Lalitpur Sub-Metropolitan City',value: 'Lalitpur Sub-Metropolitan City' },
]
