/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeeIndexRouteImport } from './routes/employee/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CompanysetupIndexRouteImport } from './routes/companysetup/index'
import { Route as CompanysetupDepartmentmanagementRouteImport } from './routes/companysetup/departmentmanagement'
import { Route as CompanysetupBranchRouteImport } from './routes/companysetup/branch'
import { Route as EmployeePersonalinformationIdRouteImport } from './routes/employee/personalinformation.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/employee/',
  path: '/employee/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanysetupIndexRoute = CompanysetupIndexRouteImport.update({
  id: '/companysetup/',
  path: '/companysetup/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanysetupDepartmentmanagementRoute =
  CompanysetupDepartmentmanagementRouteImport.update({
    id: '/companysetup/departmentmanagement',
    path: '/companysetup/departmentmanagement',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompanysetupBranchRoute = CompanysetupBranchRouteImport.update({
  id: '/companysetup/branch',
  path: '/companysetup/branch',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeePersonalinformationIdRoute =
  EmployeePersonalinformationIdRouteImport.update({
    id: '/employee/personalinformation/$id',
    path: '/employee/personalinformation/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companysetup/branch': typeof CompanysetupBranchRoute
  '/companysetup/departmentmanagement': typeof CompanysetupDepartmentmanagementRoute
  '/companysetup/': typeof CompanysetupIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/employee/personalinformation/$id': typeof EmployeePersonalinformationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companysetup/branch': typeof CompanysetupBranchRoute
  '/companysetup/departmentmanagement': typeof CompanysetupDepartmentmanagementRoute
  '/companysetup': typeof CompanysetupIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/employee': typeof EmployeeIndexRoute
  '/employee/personalinformation/$id': typeof EmployeePersonalinformationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companysetup/branch': typeof CompanysetupBranchRoute
  '/companysetup/departmentmanagement': typeof CompanysetupDepartmentmanagementRoute
  '/companysetup/': typeof CompanysetupIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/employee/personalinformation/$id': typeof EmployeePersonalinformationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companysetup/branch'
    | '/companysetup/departmentmanagement'
    | '/companysetup/'
    | '/dashboard/'
    | '/employee/'
    | '/employee/personalinformation/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/companysetup/branch'
    | '/companysetup/departmentmanagement'
    | '/companysetup'
    | '/dashboard'
    | '/employee'
    | '/employee/personalinformation/$id'
  id:
    | '__root__'
    | '/'
    | '/companysetup/branch'
    | '/companysetup/departmentmanagement'
    | '/companysetup/'
    | '/dashboard/'
    | '/employee/'
    | '/employee/personalinformation/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanysetupBranchRoute: typeof CompanysetupBranchRoute
  CompanysetupDepartmentmanagementRoute: typeof CompanysetupDepartmentmanagementRoute
  CompanysetupIndexRoute: typeof CompanysetupIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
  EmployeePersonalinformationIdRoute: typeof EmployeePersonalinformationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/': {
      id: '/employee/'
      path: '/employee'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companysetup/': {
      id: '/companysetup/'
      path: '/companysetup'
      fullPath: '/companysetup/'
      preLoaderRoute: typeof CompanysetupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companysetup/departmentmanagement': {
      id: '/companysetup/departmentmanagement'
      path: '/companysetup/departmentmanagement'
      fullPath: '/companysetup/departmentmanagement'
      preLoaderRoute: typeof CompanysetupDepartmentmanagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companysetup/branch': {
      id: '/companysetup/branch'
      path: '/companysetup/branch'
      fullPath: '/companysetup/branch'
      preLoaderRoute: typeof CompanysetupBranchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/personalinformation/$id': {
      id: '/employee/personalinformation/$id'
      path: '/employee/personalinformation/$id'
      fullPath: '/employee/personalinformation/$id'
      preLoaderRoute: typeof EmployeePersonalinformationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanysetupBranchRoute: CompanysetupBranchRoute,
  CompanysetupDepartmentmanagementRoute: CompanysetupDepartmentmanagementRoute,
  CompanysetupIndexRoute: CompanysetupIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
  EmployeePersonalinformationIdRoute: EmployeePersonalinformationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
