/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeaveIndexRouteImport } from './routes/leave/index'
import { Route as EmployeeIndexRouteImport } from './routes/employee/index'
import { Route as DocumentManagementIndexRouteImport } from './routes/documentManagement/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CompanysetupIndexRouteImport } from './routes/companysetup/index'
import { Route as AttendanceIndexRouteImport } from './routes/attendance/index'
import { Route as LeaveMyRequestRouteImport } from './routes/leave/my-request'
import { Route as LeaveLeaveBalanceRouteImport } from './routes/leave/leave-balance'
import { Route as DocumentManagementVisibilityRouteImport } from './routes/documentManagement/visibility'
import { Route as DocumentManagementVersionHistoryRouteImport } from './routes/documentManagement/versionHistory'
import { Route as DocumentManagementReviewAndApprovalRouteImport } from './routes/documentManagement/reviewAndApproval'
import { Route as DocumentManagementDocumentUploadRouteImport } from './routes/documentManagement/documentUpload'
import { Route as DocumentManagementCategoryManagementRouteImport } from './routes/documentManagement/categoryManagement'
import { Route as CompanysetupDepartmentmanagementRouteImport } from './routes/companysetup/departmentmanagement'
import { Route as CompanysetupBranchRouteImport } from './routes/companysetup/branch'
import { Route as AttendanceWorkRecordRouteImport } from './routes/attendance/work-record'
import { Route as AttendanceMyAttendanceRouteImport } from './routes/attendance/my-attendance'
import { Route as EmployeePersonalinformationIdRouteImport } from './routes/employee/personalinformation.$id'
import { Route as EmployeeAssignApprovalIdRouteImport } from './routes/employee/assign-approval.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveIndexRoute = LeaveIndexRouteImport.update({
  id: '/leave/',
  path: '/leave/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/employee/',
  path: '/employee/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentManagementIndexRoute = DocumentManagementIndexRouteImport.update({
  id: '/documentManagement/',
  path: '/documentManagement/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanysetupIndexRoute = CompanysetupIndexRouteImport.update({
  id: '/companysetup/',
  path: '/companysetup/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceIndexRoute = AttendanceIndexRouteImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveMyRequestRoute = LeaveMyRequestRouteImport.update({
  id: '/leave/my-request',
  path: '/leave/my-request',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveLeaveBalanceRoute = LeaveLeaveBalanceRouteImport.update({
  id: '/leave/leave-balance',
  path: '/leave/leave-balance',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentManagementVisibilityRoute =
  DocumentManagementVisibilityRouteImport.update({
    id: '/documentManagement/visibility',
    path: '/documentManagement/visibility',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocumentManagementVersionHistoryRoute =
  DocumentManagementVersionHistoryRouteImport.update({
    id: '/documentManagement/versionHistory',
    path: '/documentManagement/versionHistory',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocumentManagementReviewAndApprovalRoute =
  DocumentManagementReviewAndApprovalRouteImport.update({
    id: '/documentManagement/reviewAndApproval',
    path: '/documentManagement/reviewAndApproval',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocumentManagementDocumentUploadRoute =
  DocumentManagementDocumentUploadRouteImport.update({
    id: '/documentManagement/documentUpload',
    path: '/documentManagement/documentUpload',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocumentManagementCategoryManagementRoute =
  DocumentManagementCategoryManagementRouteImport.update({
    id: '/documentManagement/categoryManagement',
    path: '/documentManagement/categoryManagement',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompanysetupDepartmentmanagementRoute =
  CompanysetupDepartmentmanagementRouteImport.update({
    id: '/companysetup/departmentmanagement',
    path: '/companysetup/departmentmanagement',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompanysetupBranchRoute = CompanysetupBranchRouteImport.update({
  id: '/companysetup/branch',
  path: '/companysetup/branch',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceWorkRecordRoute = AttendanceWorkRecordRouteImport.update({
  id: '/attendance/work-record',
  path: '/attendance/work-record',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceMyAttendanceRoute = AttendanceMyAttendanceRouteImport.update({
  id: '/attendance/my-attendance',
  path: '/attendance/my-attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeePersonalinformationIdRoute =
  EmployeePersonalinformationIdRouteImport.update({
    id: '/employee/personalinformation/$id',
    path: '/employee/personalinformation/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmployeeAssignApprovalIdRoute =
  EmployeeAssignApprovalIdRouteImport.update({
    id: '/employee/assign-approval/$id',
    path: '/employee/assign-approval/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance/my-attendance': typeof AttendanceMyAttendanceRoute
  '/attendance/work-record': typeof AttendanceWorkRecordRoute
  '/companysetup/branch': typeof CompanysetupBranchRoute
  '/companysetup/departmentmanagement': typeof CompanysetupDepartmentmanagementRoute
  '/documentManagement/categoryManagement': typeof DocumentManagementCategoryManagementRoute
  '/documentManagement/documentUpload': typeof DocumentManagementDocumentUploadRoute
  '/documentManagement/reviewAndApproval': typeof DocumentManagementReviewAndApprovalRoute
  '/documentManagement/versionHistory': typeof DocumentManagementVersionHistoryRoute
  '/documentManagement/visibility': typeof DocumentManagementVisibilityRoute
  '/leave/leave-balance': typeof LeaveLeaveBalanceRoute
  '/leave/my-request': typeof LeaveMyRequestRoute
  '/attendance/': typeof AttendanceIndexRoute
  '/companysetup/': typeof CompanysetupIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/documentManagement/': typeof DocumentManagementIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/leave/': typeof LeaveIndexRoute
  '/employee/assign-approval/$id': typeof EmployeeAssignApprovalIdRoute
  '/employee/personalinformation/$id': typeof EmployeePersonalinformationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance/my-attendance': typeof AttendanceMyAttendanceRoute
  '/attendance/work-record': typeof AttendanceWorkRecordRoute
  '/companysetup/branch': typeof CompanysetupBranchRoute
  '/companysetup/departmentmanagement': typeof CompanysetupDepartmentmanagementRoute
  '/documentManagement/categoryManagement': typeof DocumentManagementCategoryManagementRoute
  '/documentManagement/documentUpload': typeof DocumentManagementDocumentUploadRoute
  '/documentManagement/reviewAndApproval': typeof DocumentManagementReviewAndApprovalRoute
  '/documentManagement/versionHistory': typeof DocumentManagementVersionHistoryRoute
  '/documentManagement/visibility': typeof DocumentManagementVisibilityRoute
  '/leave/leave-balance': typeof LeaveLeaveBalanceRoute
  '/leave/my-request': typeof LeaveMyRequestRoute
  '/attendance': typeof AttendanceIndexRoute
  '/companysetup': typeof CompanysetupIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/documentManagement': typeof DocumentManagementIndexRoute
  '/employee': typeof EmployeeIndexRoute
  '/leave': typeof LeaveIndexRoute
  '/employee/assign-approval/$id': typeof EmployeeAssignApprovalIdRoute
  '/employee/personalinformation/$id': typeof EmployeePersonalinformationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance/my-attendance': typeof AttendanceMyAttendanceRoute
  '/attendance/work-record': typeof AttendanceWorkRecordRoute
  '/companysetup/branch': typeof CompanysetupBranchRoute
  '/companysetup/departmentmanagement': typeof CompanysetupDepartmentmanagementRoute
  '/documentManagement/categoryManagement': typeof DocumentManagementCategoryManagementRoute
  '/documentManagement/documentUpload': typeof DocumentManagementDocumentUploadRoute
  '/documentManagement/reviewAndApproval': typeof DocumentManagementReviewAndApprovalRoute
  '/documentManagement/versionHistory': typeof DocumentManagementVersionHistoryRoute
  '/documentManagement/visibility': typeof DocumentManagementVisibilityRoute
  '/leave/leave-balance': typeof LeaveLeaveBalanceRoute
  '/leave/my-request': typeof LeaveMyRequestRoute
  '/attendance/': typeof AttendanceIndexRoute
  '/companysetup/': typeof CompanysetupIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/documentManagement/': typeof DocumentManagementIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/leave/': typeof LeaveIndexRoute
  '/employee/assign-approval/$id': typeof EmployeeAssignApprovalIdRoute
  '/employee/personalinformation/$id': typeof EmployeePersonalinformationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance/my-attendance'
    | '/attendance/work-record'
    | '/companysetup/branch'
    | '/companysetup/departmentmanagement'
    | '/documentManagement/categoryManagement'
    | '/documentManagement/documentUpload'
    | '/documentManagement/reviewAndApproval'
    | '/documentManagement/versionHistory'
    | '/documentManagement/visibility'
    | '/leave/leave-balance'
    | '/leave/my-request'
    | '/attendance/'
    | '/companysetup/'
    | '/dashboard/'
    | '/documentManagement/'
    | '/employee/'
    | '/leave/'
    | '/employee/assign-approval/$id'
    | '/employee/personalinformation/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance/my-attendance'
    | '/attendance/work-record'
    | '/companysetup/branch'
    | '/companysetup/departmentmanagement'
    | '/documentManagement/categoryManagement'
    | '/documentManagement/documentUpload'
    | '/documentManagement/reviewAndApproval'
    | '/documentManagement/versionHistory'
    | '/documentManagement/visibility'
    | '/leave/leave-balance'
    | '/leave/my-request'
    | '/attendance'
    | '/companysetup'
    | '/dashboard'
    | '/documentManagement'
    | '/employee'
    | '/leave'
    | '/employee/assign-approval/$id'
    | '/employee/personalinformation/$id'
  id:
    | '__root__'
    | '/'
    | '/attendance/my-attendance'
    | '/attendance/work-record'
    | '/companysetup/branch'
    | '/companysetup/departmentmanagement'
    | '/documentManagement/categoryManagement'
    | '/documentManagement/documentUpload'
    | '/documentManagement/reviewAndApproval'
    | '/documentManagement/versionHistory'
    | '/documentManagement/visibility'
    | '/leave/leave-balance'
    | '/leave/my-request'
    | '/attendance/'
    | '/companysetup/'
    | '/dashboard/'
    | '/documentManagement/'
    | '/employee/'
    | '/leave/'
    | '/employee/assign-approval/$id'
    | '/employee/personalinformation/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceMyAttendanceRoute: typeof AttendanceMyAttendanceRoute
  AttendanceWorkRecordRoute: typeof AttendanceWorkRecordRoute
  CompanysetupBranchRoute: typeof CompanysetupBranchRoute
  CompanysetupDepartmentmanagementRoute: typeof CompanysetupDepartmentmanagementRoute
  DocumentManagementCategoryManagementRoute: typeof DocumentManagementCategoryManagementRoute
  DocumentManagementDocumentUploadRoute: typeof DocumentManagementDocumentUploadRoute
  DocumentManagementReviewAndApprovalRoute: typeof DocumentManagementReviewAndApprovalRoute
  DocumentManagementVersionHistoryRoute: typeof DocumentManagementVersionHistoryRoute
  DocumentManagementVisibilityRoute: typeof DocumentManagementVisibilityRoute
  LeaveLeaveBalanceRoute: typeof LeaveLeaveBalanceRoute
  LeaveMyRequestRoute: typeof LeaveMyRequestRoute
  AttendanceIndexRoute: typeof AttendanceIndexRoute
  CompanysetupIndexRoute: typeof CompanysetupIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DocumentManagementIndexRoute: typeof DocumentManagementIndexRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
  LeaveIndexRoute: typeof LeaveIndexRoute
  EmployeeAssignApprovalIdRoute: typeof EmployeeAssignApprovalIdRoute
  EmployeePersonalinformationIdRoute: typeof EmployeePersonalinformationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave/': {
      id: '/leave/'
      path: '/leave'
      fullPath: '/leave/'
      preLoaderRoute: typeof LeaveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/': {
      id: '/employee/'
      path: '/employee'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentManagement/': {
      id: '/documentManagement/'
      path: '/documentManagement'
      fullPath: '/documentManagement/'
      preLoaderRoute: typeof DocumentManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companysetup/': {
      id: '/companysetup/'
      path: '/companysetup'
      fullPath: '/companysetup/'
      preLoaderRoute: typeof CompanysetupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/': {
      id: '/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AttendanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave/my-request': {
      id: '/leave/my-request'
      path: '/leave/my-request'
      fullPath: '/leave/my-request'
      preLoaderRoute: typeof LeaveMyRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave/leave-balance': {
      id: '/leave/leave-balance'
      path: '/leave/leave-balance'
      fullPath: '/leave/leave-balance'
      preLoaderRoute: typeof LeaveLeaveBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentManagement/visibility': {
      id: '/documentManagement/visibility'
      path: '/documentManagement/visibility'
      fullPath: '/documentManagement/visibility'
      preLoaderRoute: typeof DocumentManagementVisibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentManagement/versionHistory': {
      id: '/documentManagement/versionHistory'
      path: '/documentManagement/versionHistory'
      fullPath: '/documentManagement/versionHistory'
      preLoaderRoute: typeof DocumentManagementVersionHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentManagement/reviewAndApproval': {
      id: '/documentManagement/reviewAndApproval'
      path: '/documentManagement/reviewAndApproval'
      fullPath: '/documentManagement/reviewAndApproval'
      preLoaderRoute: typeof DocumentManagementReviewAndApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentManagement/documentUpload': {
      id: '/documentManagement/documentUpload'
      path: '/documentManagement/documentUpload'
      fullPath: '/documentManagement/documentUpload'
      preLoaderRoute: typeof DocumentManagementDocumentUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentManagement/categoryManagement': {
      id: '/documentManagement/categoryManagement'
      path: '/documentManagement/categoryManagement'
      fullPath: '/documentManagement/categoryManagement'
      preLoaderRoute: typeof DocumentManagementCategoryManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companysetup/departmentmanagement': {
      id: '/companysetup/departmentmanagement'
      path: '/companysetup/departmentmanagement'
      fullPath: '/companysetup/departmentmanagement'
      preLoaderRoute: typeof CompanysetupDepartmentmanagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companysetup/branch': {
      id: '/companysetup/branch'
      path: '/companysetup/branch'
      fullPath: '/companysetup/branch'
      preLoaderRoute: typeof CompanysetupBranchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/work-record': {
      id: '/attendance/work-record'
      path: '/attendance/work-record'
      fullPath: '/attendance/work-record'
      preLoaderRoute: typeof AttendanceWorkRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/my-attendance': {
      id: '/attendance/my-attendance'
      path: '/attendance/my-attendance'
      fullPath: '/attendance/my-attendance'
      preLoaderRoute: typeof AttendanceMyAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/personalinformation/$id': {
      id: '/employee/personalinformation/$id'
      path: '/employee/personalinformation/$id'
      fullPath: '/employee/personalinformation/$id'
      preLoaderRoute: typeof EmployeePersonalinformationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/assign-approval/$id': {
      id: '/employee/assign-approval/$id'
      path: '/employee/assign-approval/$id'
      fullPath: '/employee/assign-approval/$id'
      preLoaderRoute: typeof EmployeeAssignApprovalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceMyAttendanceRoute: AttendanceMyAttendanceRoute,
  AttendanceWorkRecordRoute: AttendanceWorkRecordRoute,
  CompanysetupBranchRoute: CompanysetupBranchRoute,
  CompanysetupDepartmentmanagementRoute: CompanysetupDepartmentmanagementRoute,
  DocumentManagementCategoryManagementRoute:
    DocumentManagementCategoryManagementRoute,
  DocumentManagementDocumentUploadRoute: DocumentManagementDocumentUploadRoute,
  DocumentManagementReviewAndApprovalRoute:
    DocumentManagementReviewAndApprovalRoute,
  DocumentManagementVersionHistoryRoute: DocumentManagementVersionHistoryRoute,
  DocumentManagementVisibilityRoute: DocumentManagementVisibilityRoute,
  LeaveLeaveBalanceRoute: LeaveLeaveBalanceRoute,
  LeaveMyRequestRoute: LeaveMyRequestRoute,
  AttendanceIndexRoute: AttendanceIndexRoute,
  CompanysetupIndexRoute: CompanysetupIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DocumentManagementIndexRoute: DocumentManagementIndexRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
  LeaveIndexRoute: LeaveIndexRoute,
  EmployeeAssignApprovalIdRoute: EmployeeAssignApprovalIdRoute,
  EmployeePersonalinformationIdRoute: EmployeePersonalinformationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
